app/db_import/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField

class DBImport(FlaskForm):
    submit = SubmitField("Import data from Electoral Commission")
    

app/db_import/__init__.py
from flask import Blueprint

bp = Blueprint("db_import", __name__)

from app.db_import import routes, forms

app/db_import/routes.py
from flask import current_app, flash, redirect, render_template, url_for
from flask_login import current_user, login_required

from datetime import datetime
import glob
import re

from app.db_import import bp
from app.db_import.forms import DBImport


def last_download():
    """Finds last downloaded date"""
    root_dir = "./tests/" if current_app.config["TESTING"] else "./db/" # pragma: no cover
    raw_data_file = glob.glob("raw_data_*.csv", root_dir=root_dir)
    try:
        last_download = re.findall(r"\d{4}\-\d{2}\-\d{2}", raw_data_file[0])
        last_download = datetime.strptime(last_download[0], "%Y-%m-%d")
        last_download = last_download.strftime("%d %B %Y")
    except:  # pragma: no cover
        last_download = None
    return last_download


@bp.route("/dl_and_import", methods=["GET", "POST"])
@login_required
def dl_and_import():
    form = DBImport()
    if not form.validate_on_submit():
        return render_template(
            "db_import.html", form=form, last_download=last_download()
        )
    if current_user.get_task_in_progress():  # pragma: no cover
        flash("A database import is currently in progress.")
        return redirect(url_for("main.index"))
    current_user.launch_task()  # pragma: no cover
    return redirect(url_for("main.index"))  # pragma: no cover

app/templates/alias_detail.html
{% extends "base.html" %}

{% block app_content %}
  <h1>Alias detail: {{ alias.name }}</h1>
  <form action="" method="POST">
    {{ form.csrf_token }}
    <div class="row">
      <div class="col-sm-2">
        {{ form.alias_name.label(class_="col-form-label") }} 
      </div>
      <div class="col-sm">
        {{form.alias_name(class_="form-control") }}
      </div>
    </div>
    <div class="row">
      <div class="col-sm-2">
        {{ form.note.label(class_="col-form-label") }}
      </div>
      <div class="col-sm">
        {{form.note(class_="form-control") }}
      </div>
    </div>
    <br>
    {{ form.submit(class_="btn btn-primary") }} 
    <a href="{{ url_for('alias.delete_alias', id=alias.id)}}" class="btn btn-primary">
      Delete alias
    </a>
  </form>
  <br>
  <p>
    This alias applies to:
  </p>

  {% for donor in alias.donors %}
    <h2> {{ donor.name }} </h2>
    <p><a href="{{ url_for("alias.remove_alias", alias_id=alias.id, donor_id=donor.id) }}">Remove donor from alias</a></p>
      <table class="table">
      <thead>
        <th scope="col">Recipient</th>
        <th scope="col">Amount</th>
        <th scope="col">Date</th>
      {% for donation in donor.donations %}
        <tr>
          <td> {{ donation.recipient.name }} </td>
          <td> £{{ '{:,.2f}'.format(donation.value) }} </td>
          <td> {{ donation.date.strftime("%-d %B %Y") }} </td>
        </tr>
      {% endfor %}
      </table>
  {% endfor %}
  
{% endblock %}

{% block scripts %}
{% endblock %}

app/templates/alias_port.html
{% extends "base.html" %}

{% block app_content %}

  <h1>Import/export aliases</h1>

  <div class="row">
      <p>
        Here, you can either download the aliases in the database as a JSON file 
        or upload a previously exported JSON file. When uploading, each donor's name
        is used to find the relevant alias.
      </p>
      <form action="" method="POST" enctype="multipart/form-data">
        {{ form.csrf_token }}
            {{ form.json(class_="form-control", type_="file") }}
            {% for error in form.errors %}
              <span style="color: red; font-style: italic">{{ error }}</span>
              <br>
            {% endfor %}

            <br>
            <button type="submit" class="btn btn-primary">
              Import (overwrites all existing aliases!)
            </button>
      <a href="{{ url_for('alias.export_aliases') }}" class="btn btn-primary">
        Export as JSON
      </a>
      </form>
  </div>

{% endblock %}

{% block scripts %}
{% endblock %}

app/templates/alias_remove.html
{% extends "base.html" %}

{% block app_content %}
<h1>Confirm remove donor {{ donor.name }} from {{ alias.name }}?</h1>
  {% if full_delete %}
    <p>
      As {{ alias.name }} is the 'main alias', the only way to remove it is to entirely
      delete the alias. This will cause the following donors to be listed separately:
    </p>
    <ul>
      {% for donor in alias.donors %}
        <li> {{ donor.name }} </li>
      {% endfor %}
    </ul>

  {% else %}
    
    <p>
      Are you sure you want {{ donor.name }} to be listed separately?
    </p>

  {% endif %}  

  <div class="row">
    <div class="col-md-4">
      <form action="" method="POST">
        {{ form.csrf_token }}
        <p> <input type="submit" value="Confirm"> </p>
      </form>
    </div>
  </div>
{% endblock %}

app/templates/aliases.html
{% extends "base.html" %}

{% block app_content %}
  <h1>Aliases</h1>
  <p>
    When a political party reports a donation to the Electoral Commission, the
    Commission simply reports the donation under that name. It does not
    consolidate multiple variations of the same donor (eg "Lord
    David Sainsbury" and "Lord Sainsbury of Turville" would have multiple records). Nor
    does it consolidate the same donor's record between different political parties.
    This makes it difficult to understand how much any individual donor has given over time.
  </p>
  <p>
    The below buttons allow you to decide how Donation Whistle consolidates donor
    records. 'New Alias' adds a name and note to unaliased donors. Click on the name of
    an already-grouped alias to either change the alias or reset it (turn it back to an
    individual donor). With 'Import/Export Aliases', you can export this instance of
    Donation Whistle's aliases, either as a backup or to share your aliases with another
    instance. This also helps you import the aliases from a different instance of Donation Whistle.
  </p>

  <a href="{{ url_for('alias.create_new_alias') }}" class="btn btn-primary">
    Create new alias
  </a>
  <a href="{{ url_for('alias.import_aliases') }}" class="btn btn-primary">
    Import/export aliases
  </a>

  <br><br>
  
  {% if grouped_aliases %}
    <h2>Grouped aliases</h2>
      <ul>
        {% for alias in grouped_aliases %}
          <li>
            <a href="{{ url_for("alias.alias", id=alias.id) }}">{{ alias.name }}</a>,
            which refers to:</li>
            <ul>
              {% for donor in alias.donors %}
                <li>{{ donor.name }} </li>
              {% endfor %}            
            </ul>
        {% endfor %}      
      </ul>
  {% endif %}
  

  <h2>Ungrouped donors</h2>
    <ul>
      {% for alias in ungrouped_aliases %}
        <li>{{ alias.name }} </li>
      {% endfor %}
    </ul>
    Click here to group any of these aliases into new aliases

{% endblock %}

{% block scripts %}
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html data-bs-theme="dark">
  <head>
    {% block head %}
      <title> {{ title }} - Donation Whistle </title>
      <!-- Favicons -->
      <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
      <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
      <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
      <link href="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js">
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
      <link href="https://unpkg.com/gridjs/dist/theme/mermaid.min.css" rel="stylesheet" />
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
      <style>
        [data-column-id="amount"] {
            text-align: right;
          }
        [data-column-id="legacy"] {
            text-align: center;
          }
        th.gridjs-th {
          background-color: #424242;
          border: 0px;
          color: var(--bs-body-color);
        }
        .gridjs-td-content {
          text-align: left;
          color: var(--bs-body-color);
        }
        .filter-box {
          margin-bottom: 3px;
        }
        .gridjs-tr td {
          color: var(--bs-body-color);
          border-left: 0px;
          border-right: 0px;
          border-top: 0px;
          border-bottom: 0px;
        }
        .gridjs-tr:nth-child(odd) td {
          background: #2d2e2f;
        }
        .gridjs-tr:nth-child(even) td {
          background: #424242;
        }
        th.gridjs-th-sort:focus, th.gridjs-th-sort:hover {
          background: #2d2e2f
        }
        .gridjs-footer {
          background-color: #2d2e2f;
        }
        .gridjs-pagination {
          color: var(--bs-body-color);
        }
        .gridjs-pagination .gridjs-pages button {
          background-color:#424242;
        }
        .gridjs-pagination .gridjs-pages button.gridjs-spread {
          background-color:#424242;
        }
        .gridjs-pagination .gridjs-pages button.gridjs-currentPage {
          background-color: #2d2e2f;
        }
        .gridjs-pagination .gridjs-pages button:disabled {
          background-color:#424242;
        }
        input.gridjs-input {
          background-color: #424242;
          color: var(--bs-body-color);
        }
        .navbar {
          border-radius: 8px;
          background-color: #424242;
        }
        h1 {
          margin-top: .5em; 
          margin-bottom: .5em;
        }
      </style>
    {% endblock %}
  </head>

{% block navbar %}
<div class="container">
  <nav class="navbar navbar-expand-lg">
    <div class="container-fluid">
      <a class="navbar-brand" href="{{ url_for('main.index') }}"> Donation Whistle </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.recipients') }}">Recipients</a>
          </li>
          <a class="nav-link" href="{{ url_for('main.donors') }}">Donors</a>
          {% if current_user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link"  href="{{ url_for('alias.aliases') }}">Aliases</a>
            </li>
            <li class="nav-item">
              <a class="nav-link"  href="{{ url_for('db_import.dl_and_import') }}">Data import</a>
            </li>
            {% if current_user.is_admin %}
              <li class="nav-item">
                <a class="nav-link"  href="{{ url_for('main.users')}}">Users</a>
              </li>
            {% endif %}
            <li><a class="nav-link" href="{{ url_for('main.logout') }}">Log out</a></li>
          {% else %}
            <li><a class="nav-link" href="{{ url_for('main.login') }}">Log in</a></li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
{% endblock %}

  {% if current_user.is_authenticated %}
    {% with tasks = current_user.get_tasks_in_progress() %}
      {% if tasks %}
        {% for task in tasks %}
          <div class="alert alert-success" role="alert">
            {{ task.description }}
            Database import in progress: <span id="{{ task.id }}-progress">{{ task.get_progress() }}</span>%
          </div>
        {% endfor %}
      {% endif %}
    {% endwith %}
  {% endif %}

  {% with messages = get_flashed_messages() %}
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-info" role="alert">{{ message }}</div>
      {% endfor %}
    {% endif %}
  {% endwith %}

{% block app_content %}
{% endblock %}
</div>

  <link rel="manifest" href="site.webmanifest">

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"> </script>       
  {% if current_user.is_authenticated %}
    <script>
      function set_task_progress(task_id, progress) {
        $('#' + task_id + '-progress').text(progress);
      }
      $(function() {
        var since = 0;
        setInterval(function() {
          $.ajax('{{ url_for('main.notifications') }}?since=' + since).done(
            function(notifications) {
              if (notifications && notifications.name == 'task_progress')
              { 
                set_task_progress(
                  notifications.data.task_id,
                  notifications.data.progress
                );
                since = notifications.timestamp;
              } 
            }
          );
        }, 1000);
      });
    </script>
  {% endif %}
{% block scripts %}
{% endblock %}

{% block footer %}
  <div class="container">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
      <p class="col-md-4 mb-0 text-body-secondary">
        Learn more at
        <a href="https://www.willthong.com/donation-whistle.html">
          Will Thong's blog
        </a>
      </p>
      <a href=" /" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
        <svg class="bi me-2" width="40" height="32">
          <use xlink:href="#bootstrap"></use>
        </svg>
      </a>

      <ul class="nav col-md-4 justify-content-end">
        <li class="nav-item">
          Source code 
          <a href="https://www.github.com/willthong/donation-whistle">
            on GitHub
          </a>
        </li>
      </ul>
    </footer>
</div>
{% endblock %}

</html>

app/templates/create_new_alias.html
{% extends "base.html" %}

{% block app_content %}
  <h1>Create a new alias</h1>
  <p>
    Every time a political party reports a donation to the Electoral Commission, the
    Commission simply reports the donation under that name. The Commission does not
    perform any consolidation between multiple variations of the same donor (eg "Lord
    David Sainsbury" and "Lord Sainsbury of Turville" would have multiple records), whether
    between different political parties or to the same political party, so it is
    hard to establish how much any individual donor has given over time.
  </p>
  <p>
    Below, you can assign aliases to group together any donors who do not currently have
    an alias.
  </p>
  
  <form action="/aliases" method="post" id="aliasForm">
    <button type="button" class="btn btn-outline" disabled id="submitButton">
      <span id="submitLabel">
        Select multiple donors to apply an alias
      </span>
    </button>
    <button type="button" class="btn btn-secondary" id="clearButton">
      Clear selections
    </button>
  </form>
  <br>

 <input class="form-control" type="text" id="filterBox" onkeyup="filterDonors()" placeholder="Filter donors...">

  <div class="list-group">
    {% for alias in ungrouped_aliases %}
      <a href="#/" class="list-group-item list-group-item-action" data-id="{{alias.id}}">
        {{ alias.name }} 
      </a>
    {% endfor %}
  </div>
{% endblock %}

{% block scripts %}
  <script>
    const submitButton = document.getElementById('submitButton');
    const clearButton = document.getElementById('clearButton');
    const selectedAliases = [];
    const aliases = document.querySelectorAll('.list-group-item');
    const submitLabel = document.getElementById('submitLabel');
    
    // Script for clicking a list item
    aliases.forEach(alias => {
      alias.addEventListener('click', () => {
        const clickedItem = event.target;
        if (clickedItem.closest('.list-group')) {
          alias.classList.toggle("active");
          const aliasId = alias.getAttribute('data-id');
          if (alias.classList.contains('active')) {
            selectedAliases.push(aliasId);
          } else {
            // Check the selected alias is in selectedAliases before trying to remove it
            const index = selectedAliases.indexOf(aliasId);
            if (index !== -1) {
              selectedAliases.splice(index, 1);
            }
          }
          updateSubmitButton();
        }
      })
    });

    // Script for clicking the submit button
    submitButton.addEventListener('click', () => {
      if (selectedAliases.length > 1) {
        const queryParams = new URLSearchParams({
          selected_donors: JSON.stringify(selectedAliases) 
        });
        window.location.href = `/alias/new?${queryParams}`;
      }
    })

    clearButton.addEventListener('click', () => {
      const items = document.getElementsByClassName('active')
      while (items.length > 0) {
        const item = items[0];
        items[0].classList.remove('active')
        const index = selectedAliases.indexOf(item.getAttribute('data-id'));
        if (index !== -1) {
          selectedAliases.splice(index, 1);
        }
      }
      updateSubmitButton();
    })

    function filterDonors() {
      var items = document.getElementsByClassName('list-group-item');
      var input = document.getElementById('filterBox').value.toUpperCase(); 

      for (var i = 0; i < items.length; i++) {
        if (items[i].textContent.toUpperCase().indexOf(input) > -1) {
          items[i].style.display = "";
        } else {
          items[i].style.display = "none";
        }
      }
    }

    function updateSubmitButton() {
      const selectedCount = selectedAliases.length;
      // Update save button
      if (selectedCount > 1) {
        submitLabel.textContent = `Save alias for ${selectedCount} donors`;
        submitButton.classList.remove('btn-outline');
        submitButton.classList.add('btn-primary');
        submitButton.removeAttribute('disabled');
      }
      else if (selectedCount <= 1) {
        submitLabel.textContent = "Select multiple donors to apply an alias";
        submitButton.classList.remove('btn-primary');
        submitButton.classList.add('btn-outline');
        submitButton.setAttribute('disabled', '');
      }
    }

  </script>
{% endblock %}

app/templates/db_import.html
{% extends "base.html" %}

{% block app_content %}

  <h1>Import database</h1>

  <div class="row">
    <form action="" method="POST" enctype="multipart/form-data">
      {{ form.csrf_token }}
      <p>
        {% if last_download %}
          Data last downloaded on {{ last_download }}. The below button refreshes the
          data from the Electoral Commission's website.
        {% else %}
          No previous raw data detected.
        {% endif %}
      </p>
      <p>
        {% for error in form.errors %}
          <span style="color: red; font-style: italic">{{ error }}</span>
        {% endfor %}
        {{ form.json }}
        <button type="submit" class="btn btn-primary">Download data from Electoral Commission</button>
      </p>
    </form>
  </div>

{% endblock %}

{% block scripts %}
{% endblock %}

app/templates/new_alias_name.html
{% extends "base.html" %}

{% block app_content %}
  <h1>Confirm new alias creation?</h1>
  <form action="" method="POST">
    {{ form.csrf_token }}
    <div class="row">
      <div class="col-sm-2">
        {{ form.alias_name.label(class_="col-form-label") }}
      </div>
      <div class="col-sm-5">
        {{form.alias_name(class_="form-control") }}
      </div>
      <div class="col-sm-5">
        <span id="aliasNameHelpInline" class="form-text">
          You can also click the the donors' names below use their names
        </span>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-2">
        {{ form.note.label(class_="col-form-label") }}
      </div>
      <div class="col-sm-10">
        {{form.note(class_="form-control") }}
    </div>
    <p> {{ form.submit(class_="btn btn-primary") }} </p>
  </form>
  </div>
  {% for donor in selected_donors %}
    <h2>{{ donor.name }}</h2>
    <table class="table">
      <thead>
        <th >Recipient</th>
        <th >Amount</th>
        <th >Date</th>
      </thead>
      {% for donation in donor.donations %}
        <tr>
          <td> {{ donation.recipient.name }} </td>
          <td> £{{ '{:,.2f}'.format(donation.value) }} </td>
          <td> {{ donation.date.strftime("%-d %B %Y") }} </td>
        </tr>
      {% endfor %}
    </table>
  {% endfor %}
{% endblock %}

{% block scripts %}
  <script>
    var nameField = document.getElementById('alias_name');
    var allH2 = document.querySelectorAll("h2");

    function replaceNameField(text) {
      console.log(text)
      nameField.value = text;
    }

    for (var heading of allH2) {
      $(heading).wrap('<a href="#" onclick="replaceNameField(\'' + heading.textContent + '\')">');
    }
    
  </script>
{% endblock %}

app/templates/no_records.html
{% extends "base.html" %}

{% block head %}
  {{ super() }}
{% endblock %}

{% block app_content %}
  <h1>
    No records
  </h1>
  <p>
    Donation Whistle has not yet had any donation records imported from the Electoral
    Commission website.
    {% if current_user.is_admin %}
      Please click <a href="{{ url_for('db_import.dl_and_import') }}">data import</a> 
      to import records.
    {% else %}
      Please contact an administrator to import data.
    {% endif %}

{% endblock %}

app/templates/recipient.html
{% extends "base.html" %}

{% block head %}
  {{ super() }}
    <script src="https://cdn.plot.ly/plotly-2.25.2.min.js" charset="utf-8"></script>
{% endblock %}

{% block app_content %}

  <h1>Recipient detail: {{ recipient.name }}<br>
  </h1>
  {% if recipient.deregistered %}
    <p>
      This party has been deregistered as of {{ recipient.deregistered.strftime("%-d %B
      %Y") }}
    </p>
  {% endif %}


  <div class="row">
    <div class="col-md-2">
      <button type="button" class="btn btn-secondary" onclick="seeAllGifts()">See
        all gifts</button>
    </div>
    <div class="col-md">
      <form action="/recipient/{{ recipient.id }}" method="POST"> {{ form.csrf_token }}
        <strong>Dates</strong><br>
        <div class="row">
          <div class="col-md-1">
            {{ form.date_gt.label }} 
          </div>
          <div class="col-md">
            {{ form.date_gt }}
          </div>
        </div>
        <div class="row">
          <div class="col-md-1">
            {{ form.date_lt.label }} 
          </div>
          <div class="col-md">
            {{ form.date_lt }}
          </div>
        </div>
        <br>
      <button type="submit" class="btn btn-primary" >Apply date filter</button> 
      </form>
    </div>

  </div>
  
  <div class="row">
    <div id="topDonorGraph" style="width:1300px;height:600px;"></div>
  </div>

  <div class="row">
    <div class="col-6">
      <div id="donationSourcesGraph" style="width:500px;height:300px;">
      </div>
    </div>
    </div>
  </div>

{% endblock %}

{% block scripts %}
  <script>
    var topDonorGraph = document.getElementById('topDonorGraph');
    var topDonorGraphData = {{ top_donor_graph | safe }};
    Plotly.newPlot(topDonorGraph, topDonorGraphData);

    var donationSourcesGraph = document.getElementById('donationSourcesGraph');
    var donationSourcesGraphData = {{ donation_sources_graph | safe }};
    Plotly.newPlot(donationSourcesGraph, donationSourcesGraphData);

    // Rotate Y axis title
    var yTitle = document.querySelector('.ytitle');
    yTitle.setAttribute('transform', 'rotate(0,' + yTitle.getAttribute('x') + ',' + yTitle.getAttribute('y') + ')');

    // Disable legend interactivity
    document.querySelectorAll('.legendtoggle').forEach(function(toggle) {
      toggle.style.pointerEvents = 'none';
    });

    var filter_url = '{{ url_for('main.index') }}' + "{{ filter_list | safe }}";

    // Update dates to match URL
    const urlParams = new URLSearchParams(window.location.search);
    var dateGt = dateLt = "";

    urlParams.forEach((value, key) => {
      if (key.includes('filter') && value.includes('date_gt_')) {
        filter_url = filter_url + '&filter=' + value
        dateGt = value.replace('date_gt_', '');
      } else if (key.includes('filter') && value.includes('date_lt_')) {
        filter_url = filter_url + '&filter=' + value
        dateLt = value.replace('date_lt_', '');
      }
    });

    // Get references to the input fields
    const dateGtInput = document.getElementById('date_gt');
    const dateLtInput = document.getElementById('date_lt');

    // Set the input fields' values from the URL parameters, converting the format
    dateGtInput.value = dateGt;
    dateLtInput.value = dateLt;

    function seeAllGifts() {
      window.location.href = filter_url; return false;
    };

  </script>
{% endblock %}

app/templates/recipients.html
{% extends "base.html" %}

{% block head %}
  {{ super() }}
    <script src="https://cdn.plot.ly/plotly-2.25.2.min.js" charset="utf-8"></script>
{% endblock %}

{% block app_content %}

  <div id="graph" style="width:1300px;height:1000px;"></div>

  <p> 
    Note: these aggregations by default exclude donor types (building
    societies, public funds, impermissible donors, unidentifiable funds and "N/A" as well
    as donation types (public funds, exempt trusts, donor-exempt trusts, impermissible
    donors and unidentified donors). These are either not really gifts, negligible
    quantities or never benefit the party in question.
  </p>

  <h1>
    All recipients
  </h1>

  <div id="table"></div>

{% endblock %}


{% block scripts %}
  <script type="module">
    import { Grid, html } from "https://unpkg.com/gridjs?module";
    const currencyFormatter = (value) => new Intl.NumberFormat(
      'en-GB', 
      { 
        style: 'currency', 
        currency: 'GBP', 
        minimumFractionDigits: 2, 
        maximumFractionDigits: 2 
      }
    ).format(value);
    // Assign filterUrl so that date filters will carry through to recipient pages
    const recipientFormatter = (recipientName, recipientId) => {
      var printName = recipientName;
      if (recipientName == 'Conservative and Unionist Party') {var printName = 'Conservative Party';}
      if (recipientName == 'UK Independence Party (UKIP)') {var printName = 'UKIP';}
      if (recipientName == 'Scottish National Party (SNP)') {var printName = 'SNP';}
      return html(`<a href='recipient/${recipientId}'> ${printName} </a>`);
    }

    new Grid({
      data: [ {{ recipients|safe }} ],
      columns: [
        { 
          id: 'recipient', 
          name: 'Recipient', 
          formatter: (_, row) => recipientFormatter(row.cells[0].data, row.cells[1].data) 
        },
        { id: 'recipient_id', hidden: true },
        { id: 'amount', name: 'All time gifts', formatter: (cell) => currencyFormatter(cell) },
      ],
      search: false,
      sort: false,
      pagination: {
        enabled: true,
        limit: 50,
      },
      resizable: true,
    }).render(document.getElementById('table'));
    
    var graph = document.getElementById('graph');
    var figureData = {{ figure | safe }};
    Plotly.newPlot(graph, figureData);

    // Rotate Y axis title
    var yTitle = document.querySelector('.ytitle');
    yTitle.setAttribute('transform', 'rotate(0,' + yTitle.getAttribute('x') + ',' + yTitle.getAttribute('y') + ')');

  </script>
{% endblock %}

app/templates/users.html
{% extends "base.html" %}

{% block head %}
  {{ super() }}
  </head>
{% endblock %}

{% block app_content %}
  <h1>Users</h1>
  <div id="table"></div>
  <button type="button" class="btn btn-primary" onclick="window.location.href = '{{ url_for('main.register') }}'; return false;">Register a new user</button>
{% endblock %}

{% block scripts %}
  <script type="module">
    import { Grid, html } from "https://unpkg.com/gridjs?module";
    new Grid({
      columns: [
        {
         id: 'id',
         name: 'ID',
        },
        'Username',
        'Email',
        {
          name: 'Admin?', 
          formatter: function (cell) { 
            if (cell == 'True') {return "✅"} else {return "❌"}
          }
        },
        {
          name: 'Running database import?', 
          formatter: function (cell) { 
            if (cell == "None") {return "❌"} else {return "✅"}
          }
        },
        {
          name: 'Delete', 
          formatter: (_, row) => html(`<a href='users/delete/${row.cells[0].data}'>🗑️</a>`) 
        },
      ],
      data:[ 
        {% for user in users %}
        [
          '{{ user.id }}', 
          '{{ user.username }}', 
          '{{ user.email }}', 
          '{{ user.is_admin }}', 
          '{{ user.get_task_in_progress() }}',
          ],
        {% endfor %}
      ],
      sort: {
        enabled: true,
        multiColumn: true,
      },
      pagination: {
        enabled: true,
        limit: 100,
      },
      resizable: true,
    }).render(document.getElementById('table'));

  </script>

{% endblock %}